/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.forms;

import static interlacedventures.InterlacedVentures.checkUserName;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ApplicationFreelancer;
import models.ApplicationFreelancerDirectory;
import models.freelancer;
import models.users;
import models.FreelanceDirectory;
import models.JobsDirectory;
import models.OrdersDirectory;
import models.userDirectory;
import views.RegistrationChoiceForm;
import views.dashBoards.ViewItemsBusinessUser;
import views.dashBoards.freelancerDashboard;
import views.loginPage;


/**
 *
 * @author trishaguharoy
 */
public class freelancerRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form freelancerRegistrationForm
     */
    public freelancerRegistrationForm() {
        initComponents();
    }
    
    private String filepath2 ="";
    private String filepath1 ="";
    private String filepath3 ="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtUName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPortfolio = new javax.swing.JTextField();
        txtLatestWork = new javax.swing.JTextField();
        txtWorkExp = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        txtHourlyRate = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        comboEducation = new javax.swing.JComboBox<>();
        btnReg = new javax.swing.JButton();
        pwdField = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        jcSkills = new javax.swing.JComboBox<>();
        jlTemp = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnID = new javax.swing.JButton();
        btnViewImg = new javax.swing.JButton();
        btnVIewRes = new javax.swing.JButton();
        btnViewId = new javax.swing.JButton();
        dateField = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfName.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        tfName.setText("FREELANCER DETAILS");

        jLabel18.setText("FIRST NAME");

        jLabel19.setText("LAST NAME");

        jLabel20.setText("USERNAME");

        jLabel21.setText("AGE");

        jLabel22.setText("GENDER");

        jLabel23.setText("PHONE NUMBER");

        jLabel24.setText("EMAIL");

        jLabel25.setText("PORTFOLIO");

        jLabel26.setText("WORK EXPERIENCE");

        jLabel27.setText("LATEST WORK");

        jLabel28.setText("EDUCATION");

        jLabel29.setText("SKILL");

        jLabel30.setText("DATE OF JOINING");

        jLabel31.setText("LOCATION");

        jLabel32.setText("HOURLY RATE");

        jLabel33.setText("SET PASSWORD");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtUName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUNameMouseExited(evt);
            }
        });
        txtUName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNameActionPerformed(evt);
            }
        });

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });

        txtLatestWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatestWorkActionPerformed(evt);
            }
        });

        txtWorkExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkExpActionPerformed(evt);
            }
        });
        txtWorkExp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWorkExpKeyPressed(evt);
            }
        });

        txtLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocActionPerformed(evt);
            }
        });

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        comboEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diploma", "UnderGraduate", "Graduate", "PhD" }));

        btnReg.setText("Apply");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        pwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jcSkills.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cloud", "Hardware", "Software", "Storage", "Transport", "RawMaterials", "Auditing", "Taxation", "Creative" }));

        jlTemp.setText("temp");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("UPLOAD IMAGE ");

        btnUp.setText("upload");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        jLabel3.setText("UPLOAD RESUME");

        btnRes.setText("upload");
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });

        jLabel2.setText("UPLOAD ID");

        btnID.setText("upload");
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        btnViewImg.setText("view image");
        btnViewImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewImgActionPerformed(evt);
            }
        });

        btnVIewRes.setText("view resume");
        btnVIewRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIewResActionPerformed(evt);
            }
        });

        btnViewId.setText("view id");
        btnViewId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(btnEdit)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btnUp)
                                                            .addComponent(btnID))
                                                        .addGap(34, 34, 34)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btnViewId)
                                                            .addComponent(btnViewImg)))
                                                    .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(btnSave)
                                                .addGap(124, 124, 124)
                                                .addComponent(jlTemp)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(btnRes)
                                .addGap(18, 18, 18)
                                .addComponent(btnVIewRes))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFName)
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel22))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pwdField)
                                    .addComponent(txtPhone)
                                    .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtPortfolio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLatestWork)
                                    .addComponent(jcSkills, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLoc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(150, 482, Short.MAX_VALUE)
                                .addComponent(btnReg)
                                .addGap(85, 85, 85)
                                .addComponent(btnBack)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkExp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfName)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tfName)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(txtLatestWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(comboEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnUp)
                    .addComponent(jLabel3)
                    .addComponent(btnRes)
                    .addComponent(btnViewImg)
                    .addComponent(btnVIewRes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnID)
                            .addComponent(btnViewId))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtUNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNameActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        
        if(jcSkills.getSelectedItem().toString().equals("") ||
                txtLoc.getText().equals("") ||
                //dateField.getDate().equals("") ||
                pwdField.getPassword().equals("") ||
                txtHourlyRate.getText().equals("")||
                //Integer.parseInt(txtWorkExp.getText().equals("")) ||
                //Integer.parseInt(txtSalary.getText().equals("")) ||
                txtLatestWork.getText().equals("") ||
                comboEducation.getSelectedItem().toString().equals("") ||
                //txtSkills.getText().equals("") ||
                txtUName.getText().equals("") ||
                txtFName.getText().equals("") ||
                txtLName.getText().equals("") ||
                comboGender.getSelectedItem().toString().equals("") ||
                txtPhone.getText().equals("") ||
                filepath2.equals("")||
                filepath1.equals("")||
                filepath3.equals("")||
                txtEmail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Do Not Leave Any Field Blank");
        }
        else if(!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", txtEmail.getText()))) 
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
        
            String string = new String(pwdField.getPassword());
        ApplicationFreelancer ap = new ApplicationFreelancer(txtLoc.getText(),
                string,
                dateField.getDate(),
                Integer.parseInt(txtHourlyRate.getText()),
                txtPortfolio.getText(),
                Integer.parseInt(txtWorkExp.getText()),
                txtLatestWork.getText(),
                comboEducation.getSelectedItem().toString(),
                jcSkills.getSelectedItem().toString(),
                txtUName.getText(),
                txtFName.getText(),
                txtLName.getText(),
                Integer.parseInt(txtAge.getText()),
                comboGender.getSelectedItem().toString(),
                txtPhone.getText(),
                txtEmail.getText(),
                filepath2,
                filepath1,
                filepath3,
                "Applied");
        
        ApplicationFreelancerDirectory.getInstance().addApplicationFreelancer(ap);
        this.hide();
        loginPage lp = new loginPage();
        lp.show();
        }
        
        
//        freelancer free = new freelancer(txtLoc.getText(),
//                pwdField.getText(),
//                dateField.getDate(),
//                Integer.parseInt(txtHourlyRate.getText()),
//                txtPortfolio.getText(),
//                Integer.parseInt(txtWorkExp.getText()),
//                txtLatestWork.getText(),
//                comboEducation.getSelectedItem().toString(),
//                jcSkills.getSelectedItem().toString(),
//                txtUName.getText(),
//                txtFName.getText(),
//                txtLName.getText(),
//                Integer.parseInt(txtAge.getText()),
//                comboGender.getSelectedItem().toString(),
//                txtPhone.getText(),
//                txtEmail.getText(),
//                btnViewImg.getText(),
//                btnVIewRes.getText(),
//                btnViewId.getText());
//        
//        FreelanceDirectory.getInstance().addFreelancer(free);
//        users login = new users(txtUName.getText(),pwdField.getText(),"Freelancer");
//        userDirectory.getInstance().addUser(login);
//        
    }//GEN-LAST:event_btnRegActionPerformed

    private void txtLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //return from "view profile" button to freelancer dashboard
        if(jlTemp.getText().equals("db")){
            this.hide();
            freelancerDashboard fdb = new freelancerDashboard();
            fdb.labelFreelancer.setText(txtFName.getText());
            fdb.show();
        }
      
        else if(txtLatestWork.getText().length() > 1){
        this.hide();
        ViewItemsBusinessUser vibu = new ViewItemsBusinessUser();
        vibu.labelBUItem.setText("YOUR ORDERS");
        String[] columnNames = {"Services", "Organisation Involved", "Date", "Status"};
        int n = OrdersDirectory.getInstance().getOrdersDir().size() + JobsDirectory.getInstance().getJobsDir().size();
        String[][] rows = new String[n][4];
        int j=0;
        for(int i = 0;  i< OrdersDirectory.getInstance().getOrdersDir().size(); i++){
            if(OrdersDirectory.getInstance().getOrdersDir().get(i).getOrderedBy().equals(txtLatestWork.getText()) && !OrdersDirectory.getInstance().getOrdersDir().get(i).getStatus().equals("Closed")){
                rows[j][0] = OrdersDirectory.getInstance().getOrdersDir().get(i).getService();
                rows[j][1] = OrdersDirectory.getInstance().getOrdersDir().get(i).getRequestTo();
                Format formatter = new SimpleDateFormat("yyyy-MM-dd");
                String s = formatter.format(OrdersDirectory.getInstance().getOrdersDir().get(i).getDate());
                rows[j][2] = s;               
                rows[j][3] = OrdersDirectory.getInstance().getOrdersDir().get(i).getStatus();
                j++; 
            }     
        }
        j = 0;
        for(int i = 0; i< JobsDirectory.getInstance().getJobsDir().size(); i++){
            if(JobsDirectory.getInstance().getJobsDir().get(i).getListedBy().equals(txtLatestWork.getText())){
                rows[j][0] = JobsDirectory.getInstance().getJobsDir().get(i).getRole();
                rows[j][1] = JobsDirectory.getInstance().getJobsDir().get(i).getAppliedBy();
                Format formatter = new SimpleDateFormat("yyyy-MM-dd");
                String s = formatter.format(JobsDirectory.getInstance().getJobsDir().get(i).getDateOfListing());
                rows[j][2] = s;             
                rows[j][3] = JobsDirectory.getInstance().getJobsDir().get(i).getStatus();
                j++; 
            }     
        }
        
        DefaultTableModel dtm = new DefaultTableModel (rows, columnNames);
        vibu.tableBills.setModel(dtm);
        
        vibu.labelName.setText(txtLatestWork.getText());
        
        vibu.show();
        }
        
        
        else{
        this.hide();
        RegistrationChoiceForm rcf = new RegistrationChoiceForm();
        rcf.show();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtWorkExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkExpActionPerformed

    private void txtLatestWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatestWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatestWorkActionPerformed

    private void pwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.txtFName.setEditable(true);                  
                    this.txtLName.setEditable(true);                  
                    this.txtEmail.setEditable(true);               
                    this.comboGender.setEditable(true);
                    this.txtPhone.setEditable(true);
                    this.txtLoc.setEditable(true);
                    this.txtHourlyRate.setEditable(true);           
                    this.btnSave.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String UName = txtUName.getText();
        
        
         freelancer free = new freelancer(
                 txtLoc.getText(),
                pwdField.getText(),
                dateField.getDate(),
                Integer.parseInt(txtHourlyRate.getText()),
                txtPortfolio.getText(),
                Integer.parseInt(txtWorkExp.getText()),
                txtLatestWork.getText(),
                comboEducation.getSelectedItem().toString(),
                jcSkills.getSelectedItem().toString(),
                txtUName.getText(),
                txtFName.getText(),
                txtLName.getText(),
                Integer.parseInt(txtAge.getText()),
                comboGender.getSelectedItem().toString(),
                txtPhone.getText(),
                txtEmail.getText(),
                btnViewImg.getText(),
                btnVIewRes.getText(),
                btnViewId.getText());
        for(int i = 0; i < FreelanceDirectory.getInstance().getFreeLancerDir().size(); i++){
        if(FreelanceDirectory.getInstance().getFreeLancerDir().get(i).getUsername().equals(UName)){
            FreelanceDirectory.getInstance().updateFreelancer(free, i);
            JOptionPane.showMessageDialog(this, "Information Updated");
            }
        }
        this.hide();
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int selected = fileChooser.showOpenDialog(this);
        try{
            if(selected == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                filepath2 = file.getAbsolutePath();
                //txtImage.setText(filepath2);
            } 
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "File Not Uploaded");
        }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int selected = fileChooser.showOpenDialog(this);
        try{
            if(selected == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                filepath1 = file.getAbsolutePath();
                //txtRes.setText(filepath1);
            } 
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "File Not Uploaded");
        }
    }//GEN-LAST:event_btnResActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int selected = fileChooser.showOpenDialog(this);
        try{
            if(selected == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                filepath3 = file.getAbsolutePath();
                //txtID.setText(filepath3);
            } 
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "File Not Uploaded");
        }
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnViewImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewImgActionPerformed
        // TODO add your handling code here:
        try{
            File pdf1 = new File(filepath2);
            if(pdf1.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(pdf1);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Desktop is not supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "FIle does not exist");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnViewImgActionPerformed

    private void btnVIewResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIewResActionPerformed
        // TODO add your handling code here:
        try{
            File pdf1 = new File(filepath1);
            if(pdf1.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(pdf1);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Desktop is not supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "FIle does not exist");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnVIewResActionPerformed

    private void btnViewIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewIdActionPerformed
        // TODO add your handling code here:
        try{
            File pdf1 = new File(filepath3);
            if(pdf1.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(pdf1);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Desktop is not supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "FIle does not exist");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnViewIdActionPerformed

    private void txtUNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUNameMouseExited
        // TODO add your handling code here:
            if(!checkUserName(txtUName.getText())){
                    JOptionPane.showMessageDialog(this, "This userName is already taken, please choose a new one");
                    txtUName.setText("");
                }
    }//GEN-LAST:event_txtUNameMouseExited

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
        String phoneNumber = txtPhone.getText();
        int len = phoneNumber.length();
        
        char phoneChar = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(len<10)
            {
                txtPhone.setEditable(true);    
            }
            else
            {
                txtPhone.setEditable(false);
            }  
        }
        else
        {
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE)
            {
                txtPhone.setEditable(true);
            }
            else
            {
                txtPhone.setEditable(false);
            }
        }
        
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        char ageChar = evt.getKeyChar();
        if(Character.isLetter(ageChar))
        {
            txtAge.setEditable(false);    
        }
        else
        {
            txtAge.setEditable(true);
        }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtWorkExpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWorkExpKeyPressed
        // TODO add your handling code here:
        char workChar = evt.getKeyChar();
        if(Character.isLetter(workChar))
        {
            txtWorkExp.setEditable(false);    
        }
        else
        {
            txtWorkExp.setEditable(true);
        }
    }//GEN-LAST:event_txtWorkExpKeyPressed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(freelancerRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(freelancerRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(freelancerRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(freelancerRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new freelancerRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnEdit;
    private javax.swing.JButton btnID;
    public javax.swing.JButton btnReg;
    private javax.swing.JButton btnRes;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnVIewRes;
    private javax.swing.JButton btnViewId;
    private javax.swing.JButton btnViewImg;
    public javax.swing.JComboBox<String> comboEducation;
    public javax.swing.JComboBox<String> comboGender;
    public com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    public javax.swing.JComboBox<String> jcSkills;
    public javax.swing.JLabel jlTemp;
    public javax.swing.JPasswordField pwdField;
    public javax.swing.JLabel tfName;
    public javax.swing.JTextField txtAge;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFName;
    public javax.swing.JTextField txtHourlyRate;
    public javax.swing.JTextField txtLName;
    public javax.swing.JTextField txtLatestWork;
    public javax.swing.JTextField txtLoc;
    public javax.swing.JTextField txtPhone;
    public javax.swing.JTextField txtPortfolio;
    public javax.swing.JTextField txtUName;
    public javax.swing.JTextField txtWorkExp;
    // End of variables declaration//GEN-END:variables
}
