/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.forms;

import javax.swing.table.DefaultTableModel;
import models.Application;
import models.ApplicationDirectory;
import models.ApplicationFreelancer;
import models.ApplicationFreelancerDirectory;
import models.EmployeeDirectory;
import models.FreelanceDirectory;
import models.employee;
import models.freelancer;
import models.userDirectory;
import models.users;
import views.dashBoards.FinAndLegalDashBoard;
import views.dashBoards.OperationsAdminDashboard;
import views.dashBoards.TechAdminDashboard;

/**
 *
 * @author shreyasisodiya
 */
public class ViewInterViewRequestsForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewInterViewRequestsForm
     */
    public ViewInterViewRequestsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDisplay = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDisapprove = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbDisplay);

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDisapprove.setText("Disapprove");
        btnDisapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisapproveActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbltitle.setText("Interview Requests For");

        lblName.setText("Name");

        jButton4.setText("View Resume");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnDisapprove)
                                .addGap(72, 72, 72)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnDisapprove)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(lblName.getText().equals("TechAdmin")){
            TechAdminDashboard ta = new TechAdminDashboard();
            ta.show();
            dispose();
        }
        else if(lblName.getText().equals("Operations Admin")){
            OperationsAdminDashboard oa = new OperationsAdminDashboard();
            oa.show();
            dispose();
        }
        else if(lblName.getText().equals("Financial Admin")){
            FinAndLegalDashBoard fd = new FinAndLegalDashBoard();
            fd.show();
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        DefaultTableModel tableModel = (DefaultTableModel) tbDisplay.getModel();
        String UName = tableModel.getValueAt(tbDisplay.getSelectedRow(), 2).toString();
            
            for(int  i = 0; i < ApplicationDirectory.getInstance().getApplicationDir().size(); i++){
                
                if(ApplicationDirectory.getInstance().getApplicationDir().get(i).getUsername().equals(UName)){
                    
                    
                    employee free = new employee(
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getOrganisation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLocation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getDateOfJoining(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getPassword(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getRole(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getWorkEx(),
            10000,
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLatestWork(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getEducation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getSkills(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getUsername(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getFirstName(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLastName(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getAge(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getGender(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getPhoneNumber(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getEmail(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getImagePath(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getResPath(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getIdPath(),
            true);
            
        EmployeeDirectory.getInstance().addEmployee(free);
        
        users login = new users(UName,
                ApplicationDirectory.getInstance().getApplicationDir().get(i).getPassword(),
                "Employee");
        userDirectory.getInstance().addUser(login);
        
        
              
            Application app = new Application(
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getOrganisation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLocation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getDateOfJoining(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getPassword(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getRole(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getWorkEx(),
            10000,
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLatestWork(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getEducation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getSkills(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getUsername(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getFirstName(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLastName(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getAge(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getGender(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getPhoneNumber(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getEmail(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getImagePath(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getResPath(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getIdPath(),
            true,
            "Completed");
                        
                    ApplicationDirectory.getInstance().updateApplication(app, i);
                
             
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDisapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisapproveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tbDisplay.getModel();
        String UName = tableModel.getValueAt(tbDisplay.getSelectedRow(), 2).toString();
            
            for(int  i = 0; i < ApplicationDirectory.getInstance().getApplicationDir().size(); i++){
                
                if(ApplicationDirectory.getInstance().getApplicationDir().get(i).getUsername().equals(UName)){
                    
            Application app = new Application(
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getOrganisation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLocation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getDateOfJoining(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getPassword(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getRole(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getWorkEx(),
            10000,
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLatestWork(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getEducation(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getSkills(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getUsername(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getFirstName(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getLastName(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getAge(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getGender(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getPhoneNumber(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getEmail(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getImagePath(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getResPath(),
            ApplicationDirectory.getInstance().getApplicationDir().get(i).getIdPath(),
            true,
            "Completed");
                        
            ApplicationDirectory.getInstance().updateApplication(app, i);
                
             
                }
            }
        
    }//GEN-LAST:event_btnDisapproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInterViewRequestsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInterViewRequestsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInterViewRequestsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInterViewRequestsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInterViewRequestsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDisapprove;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblName;
    private javax.swing.JLabel lbltitle;
    public javax.swing.JTable tbDisplay;
    // End of variables declaration//GEN-END:variables
}
